version: '3'

services: 
    api:
        depends_on: 
            - mysql
        restart: always
        build: ./api
        ports: 
            - 5555:5000
    frontend:
        restart: always
        build: ./frontend
        ports: 
            - 3030:3000
    mysql:
        restart: always
        image: mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=time_db
        volumes: 
            - mysql_data:/var/lib/mysql
    adminer:
        restart: always
        image: adminer
        ports: 
            - 8888:8080

volumes: 
    mysql_data:
